# Stage 1: Build the application
FROM openjdk:21-jdk-slim as build
WORKDIR /app
COPY .mvn/ .mvn
COPY mvnw pom.xml ./
RUN ./mvnw dependency:go-offline

COPY src ./src
RUN ./mvnw package -DskipTests

# Stage 2: Create the final image
FROM openjdk:21-jdk-slim
WORKDIR /app
COPY --from=build /app/target/BlogPost-0.0.1-SNAPSHOT.jar BlogPost-0.0.1-SNAPSHOT.jar
EXPOSE 8082
ENTRYPOINT ["java", "-jar", "BlogPost-0.0.1-SNAPSHOT.jar"]