# -------- Stage 1: Build with Maven --------
FROM maven:3.8.5-openjdk-17 AS build

WORKDIR /app
COPY . .

RUN mvn clean package -DskipTests

# -------- Stage 2: Run with Java --------
FROM openjdk:17-jdk-slim

WORKDIR /app

# Stage 2: Create the final image
COPY --from=build /app/target/BlogPost-0.0.1-SNAPSHOT.jar BlogPost-0.0.1-SNAPSHOT.jar
EXPOSE 8082
ENTRYPOINT ["java", "-jar", "BlogPost-0.0.1-SNAPSHOT.jar"]